Fix application of  'external' label when external is set to True (#329)
My previous PR #328 did not do the job - the labels were added to the wrong place. Have added tests this time.

Before fix:
```
~/go-rules [fix-external-label*]$ plz test test/... --rerun
Fail: //test/labels:labels_test   0 passed   0 skipped   0 failed   1 errored Took 740ms
Error: TestFailed in labels_test
Test failed
exit status 1
Standard output:
targets_with_external_label.txt doesnt contain //:benchmark_test
//:labels_test, it contains 

//test/labels:labels_test 1 test run in 736ms; 0 passed, 1 errored
22 test targets and 29 tests run; 26 passed, 1 errored, 2 skipped.
Total time: 1m25.58s real, 8m25.03s compute.
Messages:
11:28:19.675   ERROR: //test/labels:labels_test failed: Test failed
```

After fix:

```
~/go-rules [fix-external-label]$ plz test test/... --rerun
//test/asm/lib:asm_test 1 test run in 5ms; 1 passed
//test/asm/third_party:asm_test 1 test run in 32ms; 1 passed
//test/benchmark:benchmark_test 1 test run in 2.04s; 1 passed
//test/buildinfo:buildinfo_test 1 test run in 24ms; 1 passed
//test/cgo:cgo_test 2 tests run in 27ms; 2 passed
//test/cgo_optional:cgo_optional_test 1 test run in 6ms; 1 passed
//test/definitions:definitions_test 1 test run in 74ms; 1 passed
//test/embed:embed_test 3 tests run in 7ms; 3 passed
//test/external:external_test 5 tests run in 31ms; 3 passed, 2 skipped
//test/go_repo:go_repo_test 1 test run in 1m8.353s; 1 passed
//test/go_repo_transitive_deps:go_repo_transitive_deps_test 1 test run in 1m6.839s; 1 passed
//test/go_test_compat:go_test_compat_test 1 test run in 1m4.155s; 1 passed
//test/import:import_test 2 tests run in 28ms; 2 passed
//test/importpath:importpath_test 1 test run in 16ms; 1 passed
//test/labels:labels_test 1 test run in 788ms; 1 passed
//test/large_packages:large_package_test 1 test run in 1m24.603s; 1 passed
//test/require_provide:require_provide_test 1 test run in 19ms; 1 passed
//test/root_test:root_test 1 test run in 1m15.309s; 1 passed
//test/testing_definition:testing_definition_test 1 test run in 28ms; 1 passed
//test/toolchain:freebsd_arm_toolchain_test 1 test run in 1m16.781s; 1 passed
//test/toolchain:toolchain_test 1 test run in 1m9.868s; 1 passed
22 test targets and 29 tests run; 27 passed, 2 skipped.
Total time: 1m26.26s real, 8m29.04s compute.
```